service:
  name: ${self:custom.name}

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  profile: my

custom:
  name: nuxt-on-lambda

package:
  excludeDevDependencies: true
  exclude:
    - .**
    - .**/*
    - LICENSE
    - README.md
    - package.json
    - yarn.lock
    - node_modules/babel**/**
    - node_modules/caniuse-db/**
    - node_modules/caniuse-lite/**
    - node_modules/prettier/**
    - node_modules/yargs/**
    - node_modules/postcss**/**
    - node_modules/cssnano/**
    - node_modules/xxhashjs/**
    - node_modules/jschardet/**
    - node_modules/**/*.md
    - node_modules/**/bin/**
  include:
    - server/**
    - configs/**
    - nuxt.config.js


functions:
  hello:
    handler: server/handler.handler
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get

